name: CI trabalho final

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Subir a API REST
      run: npm start &

    - name: Subir a API GraphQL
      run: npm run start-graphql &

    - name: Esperar as APIs estarem funcionando
      run: sleep 8

    - name: Rodar os testes de API viacontroller
      run: npm run test-controller

    - name: Rodar os testes de API via HTTP
      run: npm run test-external

    - name: Rodar os testes de API GraphQL
      run: npm run test-graphql